/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.globant.tc.scooter.accounts.api;

import com.globant.tc.scooter.accounts.model.InlineObject4;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-20T04:57:43.215273600+05:00[Asia/Karachi]")
@Validated
@Api(value = "buyCreditsMercadoPago", description = "the buyCreditsMercadoPago API")
public interface BuyCreditsMercadoPagoApi {

    default BuyCreditsMercadoPagoApiDelegate getDelegate() {
        return new BuyCreditsMercadoPagoApiDelegate() {};
    }

    /**
     * POST /buyCreditsMercadoPago : Buy credits in Mercado Pago
     *
     * @param inlineObject4  (required)
     * @return Operation success (status code 200)
     */
    @ApiOperation(value = "Buy credits in Mercado Pago", nickname = "buyCreditsMercadoPagoPost", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Operation success") })
    @PostMapping(
        value = "/buyCreditsMercadoPago",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> buyCreditsMercadoPagoPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody InlineObject4 inlineObject4) {
        return getDelegate().buyCreditsMercadoPagoPost(inlineObject4);
    }

}
